<?php

/**
 * BasePosyView
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property integer $grporder
 * @property Doctrine_Collection $PosyViewList
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getDescription()  Returns the current record's "description" value
 * @method integer             getGrporder()     Returns the current record's "grporder" value
 * @method Doctrine_Collection getPosyViewList() Returns the current record's "PosyViewList" collection
 * @method PosyView            setName()         Sets the current record's "name" value
 * @method PosyView            setDescription()  Sets the current record's "description" value
 * @method PosyView            setGrporder()     Sets the current record's "grporder" value
 * @method PosyView            setPosyViewList() Sets the current record's "PosyViewList" collection
 * 
 * @package    donbuket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosyView extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('posy_view');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 3000, array(
             'type' => 'string',
             'length' => 3000,
             ));
        $this->hasColumn('grporder', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PosyViewList', array(
             'local' => 'id',
             'foreign' => 'posyview_id'));
    }
}