<?php

/**
 * BaseColorList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $ColorListElement
 * 
 * @method Doctrine_Collection getColorListElement() Returns the current record's "ColorListElement" collection
 * @method ColorList           setColorListElement() Sets the current record's "ColorListElement" collection
 * 
 * @package    donbuket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseColorList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('color_list');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ColorListElement', array(
             'local' => 'id',
             'foreign' => 'list_id'));
    }
}