<?php

/**
 * BaseSeason
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $sorder
 * @property Doctrine_Collection $Flower
 * 
 * @method string              getName()   Returns the current record's "name" value
 * @method integer             getSorder() Returns the current record's "sorder" value
 * @method Doctrine_Collection getFlower() Returns the current record's "Flower" collection
 * @method Season              setName()   Sets the current record's "name" value
 * @method Season              setSorder() Sets the current record's "sorder" value
 * @method Season              setFlower() Sets the current record's "Flower" collection
 * 
 * @package    donbuket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeason extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('season');
        $this->hasColumn('name', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 40,
             ));
        $this->hasColumn('sorder', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Flower', array(
             'local' => 'id',
             'foreign' => 'season_end'));
    }
}