<?php

/**
 * BasePosy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $client_made
 * @property integer $numlinks
 * @property string $name
 * @property string $description
 * @property timestamp $published_at
 * @property timestamp $created_at
 * @property enum $price_type
 * @property float $const_price
 * @property string $icon
 * @property integer $publisher_id
 * @property integer $author_id
 * @property integer $album_id
 * @property SiteUser $SiteUser
 * @property PhotoAlbum $PhotoAlbum
 * @property Doctrine_Collection $PosyViewList
 * @property Doctrine_Collection $FlowerPosy
 * @property Doctrine_Collection $UsedProducts
 * @property Doctrine_Collection $Orders
 * 
 * @method boolean             getClientMade()   Returns the current record's "client_made" value
 * @method integer             getNumlinks()     Returns the current record's "numlinks" value
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getDescription()  Returns the current record's "description" value
 * @method timestamp           getPublishedAt()  Returns the current record's "published_at" value
 * @method timestamp           getCreatedAt()    Returns the current record's "created_at" value
 * @method enum                getPriceType()    Returns the current record's "price_type" value
 * @method float               getConstPrice()   Returns the current record's "const_price" value
 * @method string              getIcon()         Returns the current record's "icon" value
 * @method integer             getPublisherId()  Returns the current record's "publisher_id" value
 * @method integer             getAuthorId()     Returns the current record's "author_id" value
 * @method integer             getAlbumId()      Returns the current record's "album_id" value
 * @method SiteUser            getSiteUser()     Returns the current record's "SiteUser" value
 * @method PhotoAlbum          getPhotoAlbum()   Returns the current record's "PhotoAlbum" value
 * @method Doctrine_Collection getPosyViewList() Returns the current record's "PosyViewList" collection
 * @method Doctrine_Collection getFlowerPosy()   Returns the current record's "FlowerPosy" collection
 * @method Doctrine_Collection getUsedProducts() Returns the current record's "UsedProducts" collection
 * @method Doctrine_Collection getOrders()       Returns the current record's "Orders" collection
 * @method Posy                setClientMade()   Sets the current record's "client_made" value
 * @method Posy                setNumlinks()     Sets the current record's "numlinks" value
 * @method Posy                setName()         Sets the current record's "name" value
 * @method Posy                setDescription()  Sets the current record's "description" value
 * @method Posy                setPublishedAt()  Sets the current record's "published_at" value
 * @method Posy                setCreatedAt()    Sets the current record's "created_at" value
 * @method Posy                setPriceType()    Sets the current record's "price_type" value
 * @method Posy                setConstPrice()   Sets the current record's "const_price" value
 * @method Posy                setIcon()         Sets the current record's "icon" value
 * @method Posy                setPublisherId()  Sets the current record's "publisher_id" value
 * @method Posy                setAuthorId()     Sets the current record's "author_id" value
 * @method Posy                setAlbumId()      Sets the current record's "album_id" value
 * @method Posy                setSiteUser()     Sets the current record's "SiteUser" value
 * @method Posy                setPhotoAlbum()   Sets the current record's "PhotoAlbum" value
 * @method Posy                setPosyViewList() Sets the current record's "PosyViewList" collection
 * @method Posy                setFlowerPosy()   Sets the current record's "FlowerPosy" collection
 * @method Posy                setUsedProducts() Sets the current record's "UsedProducts" collection
 * @method Posy                setOrders()       Sets the current record's "Orders" collection
 * 
 * @package    donbuket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('posy');
        $this->hasColumn('client_made', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('numlinks', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 3000, array(
             'type' => 'string',
             'length' => 3000,
             ));
        $this->hasColumn('published_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('price_type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'unknown',
              1 => 'constant',
              2 => 'variable',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('const_price', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('icon', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('publisher_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('author_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('album_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SiteUser', array(
             'local' => 'author_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('PhotoAlbum', array(
             'local' => 'album_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('PosyViewList', array(
             'local' => 'id',
             'foreign' => 'posy_id'));

        $this->hasMany('FlowerPosy', array(
             'local' => 'id',
             'foreign' => 'posy_id'));

        $this->hasMany('UsedProducts', array(
             'local' => 'id',
             'foreign' => 'posy_id'));

        $this->hasMany('Orders', array(
             'local' => 'id',
             'foreign' => 'posy_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}