<?php

/**
 * BaseUsedProducts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $amount
 * @property integer $product_id
 * @property integer $posy_id
 * @property Product $Product
 * @property Posy $Posy
 * 
 * @method integer      getAmount()     Returns the current record's "amount" value
 * @method integer      getProductId()  Returns the current record's "product_id" value
 * @method integer      getPosyId()     Returns the current record's "posy_id" value
 * @method Product      getProduct()    Returns the current record's "Product" value
 * @method Posy         getPosy()       Returns the current record's "Posy" value
 * @method UsedProducts setAmount()     Sets the current record's "amount" value
 * @method UsedProducts setProductId()  Sets the current record's "product_id" value
 * @method UsedProducts setPosyId()     Sets the current record's "posy_id" value
 * @method UsedProducts setProduct()    Sets the current record's "Product" value
 * @method UsedProducts setPosy()       Sets the current record's "Posy" value
 * 
 * @package    donbuket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsedProducts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('used_products');
        $this->hasColumn('amount', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('posy_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Posy', array(
             'local' => 'posy_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}