<?php

/**
 * BaseFlowerPosy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $amount
 * @property integer $flower_id
 * @property integer $posy_id
 * @property Flower $Flower
 * @property Posy $Posy
 * 
 * @method integer    getAmount()    Returns the current record's "amount" value
 * @method integer    getFlowerId()  Returns the current record's "flower_id" value
 * @method integer    getPosyId()    Returns the current record's "posy_id" value
 * @method Flower     getFlower()    Returns the current record's "Flower" value
 * @method Posy       getPosy()      Returns the current record's "Posy" value
 * @method FlowerPosy setAmount()    Sets the current record's "amount" value
 * @method FlowerPosy setFlowerId()  Sets the current record's "flower_id" value
 * @method FlowerPosy setPosyId()    Sets the current record's "posy_id" value
 * @method FlowerPosy setFlower()    Sets the current record's "Flower" value
 * @method FlowerPosy setPosy()      Sets the current record's "Posy" value
 * 
 * @package    donbuket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFlowerPosy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('flower_posy');
        $this->hasColumn('amount', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('flower_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('posy_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Flower', array(
             'local' => 'flower_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Posy', array(
             'local' => 'posy_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}