<?php

/**
 * BaseYearStatistic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $created_at
 * @property integer $visits
 * @property integer $orders
 * @property integer $messages
 * @property integer $authenticated_visits
 * 
 * @method date          getCreatedAt()            Returns the current record's "created_at" value
 * @method integer       getVisits()               Returns the current record's "visits" value
 * @method integer       getOrders()               Returns the current record's "orders" value
 * @method integer       getMessages()             Returns the current record's "messages" value
 * @method integer       getAuthenticatedVisits()  Returns the current record's "authenticated_visits" value
 * @method YearStatistic setCreatedAt()            Sets the current record's "created_at" value
 * @method YearStatistic setVisits()               Sets the current record's "visits" value
 * @method YearStatistic setOrders()               Sets the current record's "orders" value
 * @method YearStatistic setMessages()             Sets the current record's "messages" value
 * @method YearStatistic setAuthenticatedVisits()  Sets the current record's "authenticated_visits" value
 * 
 * @package    donbuket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseYearStatistic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('year_statistic');
        $this->hasColumn('created_at', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('visits', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('orders', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('messages', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('authenticated_visits', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}