<?php

/**
 * BaseMeasure
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $logname
 * @property Doctrine_Collection $ProductCategory
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getLogname()         Returns the current record's "logname" value
 * @method Doctrine_Collection getProductCategory() Returns the current record's "ProductCategory" collection
 * @method Measure             setName()            Sets the current record's "name" value
 * @method Measure             setLogname()         Sets the current record's "logname" value
 * @method Measure             setProductCategory() Sets the current record's "ProductCategory" collection
 * 
 * @package    donbuket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMeasure extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('measure');
        $this->hasColumn('name', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 10,
             ));
        $this->hasColumn('logname', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProductCategory', array(
             'local' => 'id',
             'foreign' => 'measure_id'));
    }
}