<?php

/**
 * BaseColorListElement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $color_id
 * @property integer $list_id
 * @property Color $Color
 * @property ColorList $ColorList
 * 
 * @method integer          getColorId()   Returns the current record's "color_id" value
 * @method integer          getListId()    Returns the current record's "list_id" value
 * @method Color            getColor()     Returns the current record's "Color" value
 * @method ColorList        getColorList() Returns the current record's "ColorList" value
 * @method ColorListElement setColorId()   Sets the current record's "color_id" value
 * @method ColorListElement setListId()    Sets the current record's "list_id" value
 * @method ColorListElement setColor()     Sets the current record's "Color" value
 * @method ColorListElement setColorList() Sets the current record's "ColorList" value
 * 
 * @package    donbuket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseColorListElement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('color_list_element');
        $this->hasColumn('color_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('list_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Color', array(
             'local' => 'color_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ColorList', array(
             'local' => 'list_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}