<?php

/**
 * BaseAlbumElement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $photo_id
 * @property integer $album_id
 * @property integer $itmorder
 * @property Photo $Photo
 * @property PhotoAlbum $PhotoAlbum
 * 
 * @method integer      getPhotoId()    Returns the current record's "photo_id" value
 * @method integer      getAlbumId()    Returns the current record's "album_id" value
 * @method integer      getItmorder()   Returns the current record's "itmorder" value
 * @method Photo        getPhoto()      Returns the current record's "Photo" value
 * @method PhotoAlbum   getPhotoAlbum() Returns the current record's "PhotoAlbum" value
 * @method AlbumElement setPhotoId()    Sets the current record's "photo_id" value
 * @method AlbumElement setAlbumId()    Sets the current record's "album_id" value
 * @method AlbumElement setItmorder()   Sets the current record's "itmorder" value
 * @method AlbumElement setPhoto()      Sets the current record's "Photo" value
 * @method AlbumElement setPhotoAlbum() Sets the current record's "PhotoAlbum" value
 * 
 * @package    donbuket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlbumElement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('album_element');
        $this->hasColumn('photo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('album_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('itmorder', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Photo', array(
             'local' => 'photo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('PhotoAlbum', array(
             'local' => 'album_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}