<?php

/**
 * BasePhotoAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $AlbumElement
 * @property Doctrine_Collection $Flower
 * 
 * @method Doctrine_Collection getAlbumElement() Returns the current record's "AlbumElement" collection
 * @method Doctrine_Collection getFlowerShop()   Returns the current record's "FlowerShop" collection
 * @method Doctrine_Collection getPosy()         Returns the current record's "Posy" collection
 * @method Doctrine_Collection getProduct()      Returns the current record's "Product" collection
 * @method Doctrine_Collection getFlower()       Returns the current record's "Flower" collection
 * @method PhotoAlbum          setAlbumElement() Sets the current record's "AlbumElement" collection
 * @method PhotoAlbum          setFlowerShop()   Sets the current record's "FlowerShop" collection
 * @method PhotoAlbum          setPosy()         Sets the current record's "Posy" collection
 * @method PhotoAlbum          setProduct()      Sets the current record's "Product" collection
 * @method PhotoAlbum          setFlower()       Sets the current record's "Flower" collectionShop
 * @property Doctrine_Collection $Posy
 * @property Doctrine_Collection $Product
 * @property Doctrine_Collection $Flower
 * 
 * @method Doctrine_Collection getAlbumElement() Returns the current record's "AlbumElement" collection
 * @method Doctrine_Collection getFlowerShop()   Returns the current record's "FlowerShop" collection
 * @method Doctrine_Collection getPosy()         Returns the current record's "Posy" collection
 * @method Doctrine_Collection getProduct()      Returns the current record's "Product" collection
 * @method Doctrine_Collection getFlower()       Returns the current record's "Flower" collection
 * @method PhotoAlbum          setAlbumElement() Sets the current record's "AlbumElement" collection
 * @method PhotoAlbum          setFlowerShop()   Sets the current record's "FlowerShop" collection
 * @method PhotoAlbum          setPosy()         Sets the current record's "Posy" collection
 * @method PhotoAlbum          setProduct()      Sets the current record's "Product" collection
 * @method PhotoAlbum          setFlower()       Sets the current record's "Flower" collection
 * 
 * @package    donbuket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhotoAlbum extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('photo_album');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AlbumElement', array(
             'local' => 'id',
             'foreign' => 'album_id'));

        $this->hasMany('FlowerShop', array(
             'local' => 'id',
             'foreign' => 'views'));

        $this->hasMany('Posy', array(
             'local' => 'id',
             'foreign' => 'album_id'));

        $this->hasMany('Product', array(
             'local' => 'id',
             'foreign' => 'album_id'));

        $this->hasMany('Flower', array(
             'local' => 'id',
             'foreign' => 'album_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}