<?php

/**
 * BaseDayStatistic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hour
 * @property integer $visits
 * @property integer $orders
 * @property integer $messages
 * @property integer $authenticated_visits
 * 
 * @method integer      getHour()                 Returns the current record's "hour" value
 * @method integer      getVisits()               Returns the current record's "visits" value
 * @method integer      getOrders()               Returns the current record's "orders" value
 * @method integer      getMessages()             Returns the current record's "messages" value
 * @method integer      getAuthenticatedVisits()  Returns the current record's "authenticated_visits" value
 * @method DayStatistic setHour()                 Sets the current record's "hour" value
 * @method DayStatistic setVisits()               Sets the current record's "visits" value
 * @method DayStatistic setOrders()               Sets the current record's "orders" value
 * @method DayStatistic setMessages()             Sets the current record's "messages" value
 * @method DayStatistic setAuthenticatedVisits()  Sets the current record's "authenticated_visits" value
 * 
 * @package    donbuket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDayStatistic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('day_statistic');
        $this->hasColumn('hour', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('visits', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('orders', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('messages', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('authenticated_visits', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}