<?php

/**
 * BasePosyViewList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $itmorder
 * @property integer $posy_id
 * @property integer $posyview_id
 * @property Posy $Posy
 * @property PosyView $PosyView
 * 
 * @method integer      getItmorder()    Returns the current record's "itmorder" value
 * @method integer      getPosyId()      Returns the current record's "posy_id" value
 * @method integer      getPosyviewId()  Returns the current record's "posyview_id" value
 * @method Posy         getPosy()        Returns the current record's "Posy" value
 * @method PosyView     getPosyView()    Returns the current record's "PosyView" value
 * @method PosyViewList setItmorder()    Sets the current record's "itmorder" value
 * @method PosyViewList setPosyId()      Sets the current record's "posy_id" value
 * @method PosyViewList setPosyviewId()  Sets the current record's "posyview_id" value
 * @method PosyViewList setPosy()        Sets the current record's "Posy" value
 * @method PosyViewList setPosyView()    Sets the current record's "PosyView" value
 * 
 * @package    donbuket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePosyViewList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('posy_view_list');
        $this->hasColumn('itmorder', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('posy_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('posyview_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Posy', array(
             'local' => 'posy_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('PosyView', array(
             'local' => 'posyview_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}