<?php

/**
 * BaseForumPost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $body
 * @property timestamp $created_at
 * @property integer $author_id
 * @property SiteUser $SiteUser
 * 
 * @method string    getBody()       Returns the current record's "body" value
 * @method timestamp getCreatedAt()  Returns the current record's "created_at" value
 * @method integer   getAuthorId()   Returns the current record's "author_id" value
 * @method SiteUser  getSiteUser()   Returns the current record's "SiteUser" value
 * @method ForumPost setBody()       Sets the current record's "body" value
 * @method ForumPost setCreatedAt()  Sets the current record's "created_at" value
 * @method ForumPost setAuthorId()   Sets the current record's "author_id" value
 * @method ForumPost setSiteUser()   Sets the current record's "SiteUser" value
 * 
 * @package    donbuket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseForumPost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('forum_post');
        $this->hasColumn('body', 'string', 8000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 8000,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('author_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SiteUser', array(
             'local' => 'author_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}