<?php

/**
 * BaseOrders
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $number
 * @property timestamp $ordered_at
 * @property timestamp $deadline
 * @property timestamp $accepted_at
 * @property timestamp $completed_at
 * @property timestamp $canceled_at
 * @property string $cancel_description
 * @property string $client_requirements
 * @property string $client_phone
 * @property string $client_name
 * @property string $client_email
 * @property float $order_amount
 * @property integer $client_id
 * @property integer $responsible_id
 * @property integer $posy_id
 * @property SiteUser $SiteUser
 * @property Posy $Posy
 * 
 * @method string    getNumber()              Returns the current record's "number" value
 * @method timestamp getOrderedAt()           Returns the current record's "ordered_at" value
 * @method timestamp getDeadline()            Returns the current record's "deadline" value
 * @method timestamp getAcceptedAt()          Returns the current record's "accepted_at" value
 * @method timestamp getCompletedAt()         Returns the current record's "completed_at" value
 * @method timestamp getCanceledAt()          Returns the current record's "canceled_at" value
 * @method string    getCancelDescription()   Returns the current record's "cancel_description" value
 * @method string    getClientRequirements()  Returns the current record's "client_requirements" value
 * @method string    getClientPhone()         Returns the current record's "client_phone" value
 * @method string    getClientName()          Returns the current record's "client_name" value
 * @method string    getClientEmail()         Returns the current record's "client_email" value
 * @method float     getOrderAmount()         Returns the current record's "order_amount" value
 * @method integer   getClientId()            Returns the current record's "client_id" value
 * @method integer   getResponsibleId()       Returns the current record's "responsible_id" value
 * @method integer   getPosyId()              Returns the current record's "posy_id" value
 * @method SiteUser  getSiteUser()            Returns the current record's "SiteUser" value
 * @method Posy      getPosy()                Returns the current record's "Posy" value
 * @method Orders    setNumber()              Sets the current record's "number" value
 * @method Orders    setOrderedAt()           Sets the current record's "ordered_at" value
 * @method Orders    setDeadline()            Sets the current record's "deadline" value
 * @method Orders    setAcceptedAt()          Sets the current record's "accepted_at" value
 * @method Orders    setCompletedAt()         Sets the current record's "completed_at" value
 * @method Orders    setCanceledAt()          Sets the current record's "canceled_at" value
 * @method Orders    setCancelDescription()   Sets the current record's "cancel_description" value
 * @method Orders    setClientRequirements()  Sets the current record's "client_requirements" value
 * @method Orders    setClientPhone()         Sets the current record's "client_phone" value
 * @method Orders    setClientName()          Sets the current record's "client_name" value
 * @method Orders    setClientEmail()         Sets the current record's "client_email" value
 * @method Orders    setOrderAmount()         Sets the current record's "order_amount" value
 * @method Orders    setClientId()            Sets the current record's "client_id" value
 * @method Orders    setResponsibleId()       Sets the current record's "responsible_id" value
 * @method Orders    setPosyId()              Sets the current record's "posy_id" value
 * @method Orders    setSiteUser()            Sets the current record's "SiteUser" value
 * @method Orders    setPosy()                Sets the current record's "Posy" value
 * 
 * @package    donbuket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrders extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orders');
        $this->hasColumn('number', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 40,
             ));
        $this->hasColumn('ordered_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('deadline', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('accepted_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('completed_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('canceled_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('cancel_description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('client_requirements', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('client_phone', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('client_name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('client_email', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('order_amount', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('responsible_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('posy_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SiteUser', array(
             'local' => 'responsible_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Posy', array(
             'local' => 'posy_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}