<?php

/**
 * BaseWebSite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $visitors_a_hour
 * @property integer $visitors_a_day
 * @property string $support_email
 * @property integer $birth_year
 * @property string $about
 * 
 * @method integer getVisitorsAHour()   Returns the current record's "visitors_a_hour" value
 * @method integer getVisitorsADay()    Returns the current record's "visitors_a_day" value
 * @method string  getSupportEmail()    Returns the current record's "support_email" value
 * @method integer getBirthYear()       Returns the current record's "birth_year" value
 * @method string  getAbout()           Returns the current record's "about" value
 * @method WebSite setVisitorsAHour()   Sets the current record's "visitors_a_hour" value
 * @method WebSite setVisitorsADay()    Sets the current record's "visitors_a_day" value
 * @method WebSite setSupportEmail()    Sets the current record's "support_email" value
 * @method WebSite setBirthYear()       Sets the current record's "birth_year" value
 * @method WebSite setAbout()           Sets the current record's "about" value
 * 
 * @package    donbuket
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWebSite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('web_site');
        $this->hasColumn('visitors_a_hour', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('visitors_a_day', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('support_email', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('birth_year', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('about', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}