<?php

/**
 * BlossomingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlossomingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlossomingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Blossoming');
    }
}