<?php

/**
 * ColorListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ColorListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ColorListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ColorList');
    }
}