<?php

/**
 * ColorListElementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ColorListElementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ColorListElementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ColorListElement');
    }
}