<?php

/**
 * FaceUptimeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FaceUptimeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FaceUptimeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FaceUptime');
    }
}