<?php

/**
 * FlowerPosyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FlowerPosyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FlowerPosyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FlowerPosy');
    }
}