<?php

/**
 * FlowerShopTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FlowerShopTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FlowerShopTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FlowerShop');
    }
}