<?php

/**
 * ForumThemeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForumThemeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForumThemeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForumTheme');
    }
}