<?php

/**
 * PhotoAlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhotoAlbumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhotoAlbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PhotoAlbum');
    }
}