<?php

/**
 * PosyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PosyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PosyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Posy');
    }
}