<?php

/**
 * PosyViewListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PosyViewListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PosyViewListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PosyViewList');
    }
}