<?php

/**
 * PosyViewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PosyViewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PosyViewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PosyView');
    }
}