<?php

/**
 * SexTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SexTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SexTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sex');
    }
}