<?php

/**
 * SunSenseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SunSenseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SunSenseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SunSense');
    }
}