<?php

/**
 * UsedProductsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsedProductsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsedProductsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsedProducts');
    }
}