<?php

/**
 * WebSiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebSiteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebSiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebSite');
    }
}