<?php

/**
 * YearStatisticTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class YearStatisticTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object YearStatisticTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('YearStatistic');
    }
}